import { db } from '@/firebase/config';
import { 
  collection, 
  doc, 
  getDoc, 
  getDocs, 
  addDoc, 
  updateDoc, 
  deleteDoc,
  writeBatch, 
  query, 
  where, 
  orderBy, 
  limit,
  onSnapshot,
  serverTimestamp,
  Timestamp
} from 'firebase/firestore';
import { Product } from '@/types/inventory';

export interface EnhancedStockAlert {
  id?: string;
  productId: string;
  productName: string;
  productSku?: string;
  categoryId?: string;
  categoryName?: string;
  alertType: 'low_stock' | 'out_of_stock' | 'overstock' | 'negative_stock' | 'reorder_point' | 'expiry_warning';
  severity: 'low' | 'medium' | 'high' | 'critical';
  currentQuantity: number;
  threshold?: number;
  recommendedAction: string;
  message: string;
  isActive: boolean;
  isAcknowledged: boolean;
  priority: number; // 1-5, 5 being highest priority
  estimatedStockoutDate?: string;
  suggestedReorderQuantity?: number;
  supplierInfo?: {
    supplierId?: string;
    supplierName?: string;
    lastPurchasePrice?: number;
    leadTime?: number; // in days
  };
  createdAt: string;
  updatedAt: string;
  acknowledgedAt?: string;
  acknowledgedBy?: string;
  resolvedAt?: string;
  resolvedBy?: string;
  notes?: string;
  autoGenerated: boolean;
  userId?: string;
}

export interface StockAlertRule {
  id?: string;
  name: string;
  description: string;
  isActive: boolean;
  alertType: EnhancedStockAlert['alertType'];
  conditions: {
    categoryIds?: string[];
    productIds?: string[];
    threshold?: number;
    thresholdType: 'fixed' | 'percentage' | 'days_of_stock';
    comparisonOperator: 'less_than' | 'less_than_equal' | 'greater_than' | 'greater_than_equal' | 'equal';
  };
  actions: {
    severity: EnhancedStockAlert['severity'];
    priority: number;
    notifyUsers?: string[];
    autoReorder?: boolean;
    emailNotification?: boolean;
    smsNotification?: boolean;
  };
  createdAt: string;
  updatedAt: string;
  createdBy?: string;
}

export interface AlertSummary {
  totalAlerts: number;
  criticalAlerts: number;
  highPriorityAlerts: number;
  mediumPriorityAlerts: number;
  lowPriorityAlerts: number;
  acknowledgedAlerts: number;
  unacknowledgedAlerts: number;
  alertsByType: Record<EnhancedStockAlert['alertType'], number>;
  alertsBySeverity: Record<EnhancedStockAlert['severity'], number>;
  recentAlerts: EnhancedStockAlert[];
  topAffectedProducts: Array<{
    productId: string;
    productName: string;
    alertCount: number;
    highestSeverity: EnhancedStockAlert['severity'];
  }>;
}

export interface StockForecast {
  productId: string;
  productName: string;
  currentStock: number;
  averageDailyUsage: number;
  estimatedStockoutDate: string;
  daysUntilStockout: number;
  recommendedReorderDate: string;
  recommendedReorderQuantity: number;
  confidence: number; // 0-1
}

export class EnhancedStockAlertsService {
  private static readonly ALERTS_COLLECTION = 'enhanced_stock_alerts';
  private static readonly ALERT_RULES_COLLECTION = 'stock_alert_rules';
  private static readonly PRODUCTS_COLLECTION = 'products';
  private static readonly STOCK_MOVEMENTS_COLLECTION = 'stock_movements';

  /**
   * Create or update stock alert
   */
  static async createAlert(alertData: Omit<EnhancedStockAlert, 'id' | 'createdAt' | 'updatedAt'>): Promise<string | null> {
    try {
      const now = new Date().toISOString();
      
      // Check if similar alert already exists and is active
      const existingAlert = await this.findExistingAlert(
        alertData.productId, 
        alertData.alertType
      );

      if (existingAlert && existingAlert.isActive) {
        // Update existing alert instead of creating duplicate
        await this.updateAlert(existingAlert.id!, {
          ...alertData,
          updatedAt: now
        });
        return existingAlert.id!;
      }

      const alertDoc = await addDoc(collection(db, this.ALERTS_COLLECTION), {
        ...alertData,
        createdAt: now,
        updatedAt: now
      });

      return alertDoc.id;
    } catch (error) {
      console.error('Error creating stock alert:', error);
      return null;
    }
  }

  /**
   * Update existing alert
   */
  static async updateAlert(
    alertId: string, 
    updates: Partial<EnhancedStockAlert>
  ): Promise<boolean> {
    try {
      const alertRef = doc(db, this.ALERTS_COLLECTION, alertId);
      await updateDoc(alertRef, {
        ...updates,
        updatedAt: new Date().toISOString()
      });
      return true;
    } catch (error) {
      console.error('Error updating stock alert:', error);
      return false;
    }
  }

  /**
   * Acknowledge alert
   */
  static async acknowledgeAlert(
    alertId: string, 
    userId?: string, 
    notes?: string
  ): Promise<boolean> {
    try {
      const now = new Date().toISOString();
      await this.updateAlert(alertId, {
        isAcknowledged: true,
        acknowledgedAt: now,
        acknowledgedBy: userId,
        notes: notes || undefined
      });
      return true;
    } catch (error) {
      console.error('Error acknowledging alert:', error);
      return false;
    }
  }

  /**
   * Resolve alert
   */
  static async resolveAlert(
    alertId: string, 
    userId?: string, 
    notes?: string
  ): Promise<boolean> {
    try {
      const now = new Date().toISOString();
      await this.updateAlert(alertId, {
        isActive: false,
        isAcknowledged: true,
        resolvedAt: now,
        resolvedBy: userId,
        notes: notes || undefined
      });
      return true;
    } catch (error) {
      console.error('Error resolving alert:', error);
      return false;
    }
  }

  /**
   * Get all active alerts
   */
  static async getActiveAlerts(
    filters?: {
      severity?: EnhancedStockAlert['severity'][];
      alertType?: EnhancedStockAlert['alertType'][];
      productIds?: string[];
      categoryIds?: string[];
      acknowledged?: boolean;
      limit?: number;
    }
  ): Promise<EnhancedStockAlert[]> {
    try {
      let q = query(
        collection(db, this.ALERTS_COLLECTION),
        where('isActive', '==', true)
      );

      if (filters?.acknowledged !== undefined) {
        q = query(q, where('isAcknowledged', '==', filters.acknowledged));
      }

      if (filters?.severity && filters.severity.length > 0) {
        q = query(q, where('severity', 'in', filters.severity));
      }

      if (filters?.alertType && filters.alertType.length > 0) {
        q = query(q, where('alertType', 'in', filters.alertType));
      }

      if (filters?.productIds && filters.productIds.length > 0) {
        q = query(q, where('productId', 'in', filters.productIds));
      }

      q = query(q, orderBy('priority', 'desc'), orderBy('createdAt', 'desc'));

      if (filters?.limit) {
        q = query(q, limit(filters.limit));
      }

      const querySnapshot = await getDocs(q);
      return querySnapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })) as EnhancedStockAlert[];

    } catch (error) {
      console.error('Error fetching active alerts:', error);
      return [];
    }
  }

  /**
   * Get alert summary and statistics
   */
  static async getAlertSummary(): Promise<AlertSummary> {
    try {
      const alerts = await this.getActiveAlerts();
      
      const summary: AlertSummary = {
        totalAlerts: alerts.length,
        criticalAlerts: 0,
        highPriorityAlerts: 0,
        mediumPriorityAlerts: 0,
        lowPriorityAlerts: 0,
        acknowledgedAlerts: 0,
        unacknowledgedAlerts: 0,
        alertsByType: {
          low_stock: 0,
          out_of_stock: 0,
          overstock: 0,
          negative_stock: 0,
          reorder_point: 0,
          expiry_warning: 0
        },
        alertsBySeverity: {
          low: 0,
          medium: 0,
          high: 0,
          critical: 0
        },
        recentAlerts: [],
        topAffectedProducts: []
      };

      // Count alerts by various criteria
      const productAlertCounts = new Map<string, {
        count: number;
        productName: string;
        highestSeverity: EnhancedStockAlert['severity'];
      }>();

      alerts.forEach(alert => {
        // Count by severity
        summary.alertsBySeverity[alert.severity]++;
        
        // Count by type
        summary.alertsByType[alert.alertType]++;
        
        // Count by acknowledgment status
        if (alert.isAcknowledged) {
          summary.acknowledgedAlerts++;
        } else {
          summary.unacknowledgedAlerts++;
        }

        // Count by priority
        if (alert.priority >= 5) summary.criticalAlerts++;
        else if (alert.priority >= 4) summary.highPriorityAlerts++;
        else if (alert.priority >= 3) summary.mediumPriorityAlerts++;
        else summary.lowPriorityAlerts++;

        // Track product alert counts
        const existing = productAlertCounts.get(alert.productId);
        if (existing) {
          existing.count++;
          if (this.getSeverityWeight(alert.severity) > this.getSeverityWeight(existing.highestSeverity)) {
            existing.highestSeverity = alert.severity;
          }
        } else {
          productAlertCounts.set(alert.productId, {
            count: 1,
            productName: alert.productName,
            highestSeverity: alert.severity
          });
        }
      });

      // Get recent alerts (last 10)
      summary.recentAlerts = alerts
        .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
        .slice(0, 10);

      // Get top affected products
      summary.topAffectedProducts = Array.from(productAlertCounts.entries())
        .map(([productId, data]) => ({
          productId,
          productName: data.productName,
          alertCount: data.count,
          highestSeverity: data.highestSeverity
        }))
        .sort((a, b) => b.alertCount - a.alertCount)
        .slice(0, 10);

      return summary;

    } catch (error) {
      console.error('Error getting alert summary:', error);
      return {
        totalAlerts: 0,
        criticalAlerts: 0,
        highPriorityAlerts: 0,
        mediumPriorityAlerts: 0,
        lowPriorityAlerts: 0,
        acknowledgedAlerts: 0,
        unacknowledgedAlerts: 0,
        alertsByType: {
          low_stock: 0,
          out_of_stock: 0,
          overstock: 0,
          negative_stock: 0,
          reorder_point: 0,
          expiry_warning: 0
        },
        alertsBySeverity: {
          low: 0,
          medium: 0,
          high: 0,
          critical: 0
        },
        recentAlerts: [],
        topAffectedProducts: []
      };
    }
  }

  /**
   * Generate stock forecasts for products
   */
  static async generateStockForecasts(
    productIds?: string[],
    daysToForecast: number = 30
  ): Promise<StockForecast[]> {
    try {
      // Get products
      let productsQuery = collection(db, this.PRODUCTS_COLLECTION);
      if (productIds && productIds.length > 0) {
        productsQuery = query(productsQuery, where('__name__', 'in', productIds)) as any;
      }

      const productsSnapshot = await getDocs(productsQuery);
      const products = productsSnapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })) as Product[];

      const forecasts: StockForecast[] = [];

      for (const product of products) {
        if (!product.id) continue;

        // Get recent stock movements for this product
        const movementsQuery = query(
          collection(db, this.STOCK_MOVEMENTS_COLLECTION),
          where('productId', '==', product.id),
          where('movementType', '==', 'out'),
          orderBy('createdAt', 'desc'),
          limit(30) // Last 30 movements
        );

        const movementsSnapshot = await getDocs(movementsQuery);
        const movements = movementsSnapshot.docs.map(doc => doc.data());

        if (movements.length === 0) continue;

        // Calculate average daily usage
        const totalDays = Math.max(1, this.calculateDaysBetween(
          movements[movements.length - 1].createdAt,
          movements[0].createdAt
        ));
        
        const totalUsage = movements.reduce((sum, movement) => sum + movement.quantity, 0);
        const averageDailyUsage = totalUsage / totalDays;

        if (averageDailyUsage <= 0) continue;

        // Calculate forecast
        const currentStock = product.quantity || 0;
        const daysUntilStockout = Math.floor(currentStock / averageDailyUsage);
        const estimatedStockoutDate = new Date();
        estimatedStockoutDate.setDate(estimatedStockoutDate.getDate() + daysUntilStockout);

        // Calculate recommended reorder date (when stock hits reorder point)
        const reorderPoint = product.reorderPoint || product.minStockLevel || 5;
        const daysUntilReorder = Math.floor((currentStock - reorderPoint) / averageDailyUsage);
        const recommendedReorderDate = new Date();
        recommendedReorderDate.setDate(recommendedReorderDate.getDate() + Math.max(0, daysUntilReorder));

        // Calculate recommended reorder quantity
        const leadTime = 7; // Default 7 days lead time
        const safetyStock = Math.ceil(averageDailyUsage * 3); // 3 days safety stock
        const recommendedReorderQuantity = Math.ceil(
          (averageDailyUsage * leadTime) + safetyStock
        );

        // Calculate confidence based on data quality
        const confidence = Math.min(1, movements.length / 10); // Higher confidence with more data points

        forecasts.push({
          productId: product.id,
          productName: product.name,
          currentStock,
          averageDailyUsage: Math.round(averageDailyUsage * 100) / 100,
          estimatedStockoutDate: estimatedStockoutDate.toISOString(),
          daysUntilStockout,
          recommendedReorderDate: recommendedReorderDate.toISOString(),
          recommendedReorderQuantity,
          confidence: Math.round(confidence * 100) / 100
        });
      }

      return forecasts.sort((a, b) => a.daysUntilStockout - b.daysUntilStockout);

    } catch (error) {
      console.error('Error generating stock forecasts:', error);
      return [];
    }
  }

  /**
   * Auto-generate alerts based on current stock levels
   */
  static async generateAutomaticAlerts(userId?: string): Promise<{
    generated: number;
    errors: string[];
  }> {
    try {
      const results = { generated: 0, errors: [] as string[] };
      
      // Get all active products
      const productsSnapshot = await getDocs(
        query(collection(db, this.PRODUCTS_COLLECTION), where('isActive', '==', true))
      );
      
      const products = productsSnapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })) as Product[];

      const batch = writeBatch(db);
      const now = new Date().toISOString();

      for (const product of products) {
        if (!product.id) continue;

        const currentQuantity = product.quantity || 0;
        const reorderPoint = product.reorderPoint || product.minStockLevel || 5;
        const maxStockLevel = product.maxStockLevel;

        // Check for out of stock
        if (currentQuantity === 0) {
          const existingAlert = await this.findExistingAlert(product.id, 'out_of_stock');
          if (!existingAlert || !existingAlert.isActive) {
            const alertRef = doc(collection(db, this.ALERTS_COLLECTION));
            batch.set(alertRef, {
              productId: product.id,
              productName: product.name,
              productSku: product.sku,
              categoryId: product.categoryId,
              categoryName: product.categoryName,
              alertType: 'out_of_stock',
              severity: 'critical',
              currentQuantity,
              threshold: 0,
              recommendedAction: 'Immediate restock required',
              message: `${product.name} is completely out of stock`,
              isActive: true,
              isAcknowledged: false,
              priority: 5,
              autoGenerated: true,
              createdAt: now,
              updatedAt: now,
              userId
            });
            results.generated++;
          }
        }
        // Check for low stock
        else if (currentQuantity <= reorderPoint) {
          const existingAlert = await this.findExistingAlert(product.id, 'low_stock');
          if (!existingAlert || !existingAlert.isActive) {
            const alertRef = doc(collection(db, this.ALERTS_COLLECTION));
            batch.set(alertRef, {
              productId: product.id,
              productName: product.name,
              productSku: product.sku,
              categoryId: product.categoryId,
              categoryName: product.categoryName,
              alertType: 'low_stock',
              severity: 'high',
              currentQuantity,
              threshold: reorderPoint,
              recommendedAction: 'Consider reordering soon',
              message: `${product.name} is running low (${currentQuantity} remaining)`,
              isActive: true,
              isAcknowledged: false,
              priority: 4,
              autoGenerated: true,
              createdAt: now,
              updatedAt: now,
              userId
            });
            results.generated++;
          }
        }

        // Check for overstock
        if (maxStockLevel && currentQuantity > maxStockLevel) {
          const existingAlert = await this.findExistingAlert(product.id, 'overstock');
          if (!existingAlert || !existingAlert.isActive) {
            const alertRef = doc(collection(db, this.ALERTS_COLLECTION));
            batch.set(alertRef, {
              productId: product.id,
              productName: product.name,
              productSku: product.sku,
              categoryId: product.categoryId,
              categoryName: product.categoryName,
              alertType: 'overstock',
              severity: 'medium',
              currentQuantity,
              threshold: maxStockLevel,
              recommendedAction: 'Consider reducing orders or running promotions',
              message: `${product.name} is overstocked (${currentQuantity} vs max ${maxStockLevel})`,
              isActive: true,
              isAcknowledged: false,
              priority: 2,
              autoGenerated: true,
              createdAt: now,
              updatedAt: now,
              userId
            });
            results.generated++;
          }
        }

        // Check for negative stock
        if (currentQuantity < 0) {
          const existingAlert = await this.findExistingAlert(product.id, 'negative_stock');
          if (!existingAlert || !existingAlert.isActive) {
            const alertRef = doc(collection(db, this.ALERTS_COLLECTION));
            batch.set(alertRef, {
              productId: product.id,
              productName: product.name,
              productSku: product.sku,
              categoryId: product.categoryId,
              categoryName: product.categoryName,
              alertType: 'negative_stock',
              severity: 'critical',
              currentQuantity,
              threshold: 0,
              recommendedAction: 'Immediate stock adjustment required',
              message: `${product.name} has negative stock (${currentQuantity})`,
              isActive: true,
              isAcknowledged: false,
              priority: 5,
              autoGenerated: true,
              createdAt: now,
              updatedAt: now,
              userId
            });
            results.generated++;
          }
        }
      }

      if (results.generated > 0) {
        await batch.commit();
      }

      return results;

    } catch (error) {
      console.error('Error generating automatic alerts:', error);
      return { generated: 0, errors: ['Failed to generate automatic alerts'] };
    }
  }

  /**
   * Subscribe to real-time alerts
   */
  static subscribeToAlerts(
    callback: (alerts: EnhancedStockAlert[]) => void,
    filters?: {
      severity?: EnhancedStockAlert['severity'][];
      acknowledged?: boolean;
    }
  ): () => void {
    let q = query(
      collection(db, this.ALERTS_COLLECTION),
      where('isActive', '==', true)
    );

    if (filters?.acknowledged !== undefined) {
      q = query(q, where('isAcknowledged', '==', filters.acknowledged));
    }

    q = query(q, orderBy('priority', 'desc'), orderBy('createdAt', 'desc'));

    return onSnapshot(q, (snapshot) => {
      const alerts = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })) as EnhancedStockAlert[];

      // Apply client-side filtering for severity if needed
      let filteredAlerts = alerts;
      if (filters?.severity && filters.severity.length > 0) {
        filteredAlerts = alerts.filter(alert => 
          filters.severity!.includes(alert.severity)
        );
      }

      callback(filteredAlerts);
    });
  }

  /**
   * Delete alert
   */
  static async deleteAlert(alertId: string): Promise<boolean> {
    try {
      await deleteDoc(doc(db, this.ALERTS_COLLECTION, alertId));
      return true;
    } catch (error) {
      console.error('Error deleting alert:', error);
      return false;
    }
  }

  /**
   * Bulk operations on alerts
   */
  static async bulkUpdateAlerts(
    alertIds: string[],
    updates: Partial<EnhancedStockAlert>
  ): Promise<{ success: number; failed: number }> {
    const results = { success: 0, failed: 0 };
    const batch = writeBatch(db);
    const now = new Date().toISOString();

    try {
      alertIds.forEach(alertId => {
        const alertRef = doc(db, this.ALERTS_COLLECTION, alertId);
        batch.update(alertRef, {
          ...updates,
          updatedAt: now
        });
      });

      await batch.commit();
      results.success = alertIds.length;
    } catch (error) {
      console.error('Error in bulk update:', error);
      results.failed = alertIds.length;
    }

    return results;
  }

  // Private helper methods

  private static async findExistingAlert(
    productId: string, 
    alertType: EnhancedStockAlert['alertType']
  ): Promise<EnhancedStockAlert | null> {
    try {
      const q = query(
        collection(db, this.ALERTS_COLLECTION),
        where('productId', '==', productId),
        where('alertType', '==', alertType),
        where('isActive', '==', true),
        limit(1)
      );

      const snapshot = await getDocs(q);
      if (snapshot.empty) return null;

      return {
        id: snapshot.docs[0].id,
        ...snapshot.docs[0].data()
      } as EnhancedStockAlert;
    } catch (error) {
      console.error('Error finding existing alert:', error);
      return null;
    }
  }

  private static getSeverityWeight(severity: EnhancedStockAlert['severity']): number {
    const weights = { low: 1, medium: 2, high: 3, critical: 4 };
    return weights[severity] || 0;
  }

  private static calculateDaysBetween(startDate: string, endDate: string): number {
    const start = new Date(startDate);
    const end = new Date(endDate);
    const diffTime = Math.abs(end.getTime() - start.getTime());
    return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  }
}