"use client";
import React, { useState, useEffect, useCallback } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Grid,
  Chip,
  Button,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Tooltip,
  Badge,
  Stack,
  Alert,
  LinearProgress,
  Tabs,
  Tab,
  Checkbox,
  FormControlLabel,
  Divider,
  Avatar,
  ListItemText,
  Menu,
  MenuList,
  MenuItem as MuiMenuItem
} from '@mui/material';
import {
  Warning as WarningIcon,
  Error as ErrorIcon,
  Info as InfoIcon,
  CheckCircle as CheckCircleIcon,
  Refresh as RefreshIcon,
  FilterList as FilterIcon,
  Notifications as NotificationsIcon,
  NotificationsActive as NotificationsActiveIcon,
  Visibility as ViewIcon,
  Check as CheckIcon,
  Close as CloseIcon,
  MoreVert as MoreVertIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown as TrendingDownIcon,
  Inventory as InventoryIcon,
  Schedule as ScheduleIcon,
  Assignment as AssignmentIcon
} from '@mui/icons-material';
import { useAuth } from '@/contexts/AuthContext';
import { EnhancedStockAlertsService, EnhancedStockAlert, AlertSummary, StockForecast } from '@/services/enhancedStockAlertsService';

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function TabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;
  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`alert-tabpanel-${index}`}
      aria-labelledby={`alert-tab-${index}`}
      {...other}
    >
      {value === index && <Box sx={{ p: 3 }}>{children}</Box>}
    </div>
  );
}

const getSeverityColor = (severity: EnhancedStockAlert['severity']) => {
  switch (severity) {
    case 'critical': return 'error';
    case 'high': return 'warning';
    case 'medium': return 'info';
    case 'low': return 'success';
    default: return 'default';
  }
};

const getSeverityIcon = (severity: EnhancedStockAlert['severity']) => {
  switch (severity) {
    case 'critical': return <ErrorIcon color="error" />;
    case 'high': return <WarningIcon color="warning" />;
    case 'medium': return <InfoIcon color="info" />;
    case 'low': return <CheckCircleIcon color="success" />;
    default: return <InfoIcon />;
  }
};

const getAlertTypeIcon = (alertType: EnhancedStockAlert['alertType']) => {
  switch (alertType) {
    case 'out_of_stock': return <ErrorIcon />;
    case 'low_stock': return <WarningIcon />;
    case 'overstock': return <TrendingUpIcon />;
    case 'negative_stock': return <TrendingDownIcon />;
    case 'reorder_point': return <NotificationsIcon />;
    case 'expiry_warning': return <ScheduleIcon />;
    default: return <InfoIcon />;
  }
};

export default function EnhancedStockAlertsDashboard() {
  const { user } = useAuth();
  const [alerts, setAlerts] = useState<EnhancedStockAlert[]>([]);
  const [summary, setSummary] = useState<AlertSummary | null>(null);
  const [forecasts, setForecasts] = useState<StockForecast[]>([]);
  const [loading, setLoading] = useState(true);
  const [tabValue, setTabValue] = useState(0);
  const [selectedAlerts, setSelectedAlerts] = useState<string[]>([]);
  const [filterDialogOpen, setFilterDialogOpen] = useState(false);
  const [detailDialogOpen, setDetailDialogOpen] = useState(false);
  const [selectedAlert, setSelectedAlert] = useState<EnhancedStockAlert | null>(null);
  const [actionMenuAnchor, setActionMenuAnchor] = useState<null | HTMLElement>(null);
  const [actionMenuAlert, setActionMenuAlert] = useState<EnhancedStockAlert | null>(null);

  // Filters
  const [filters, setFilters] = useState({
    severity: [] as EnhancedStockAlert['severity'][],
    alertType: [] as EnhancedStockAlert['alertType'][],
    acknowledged: undefined as boolean | undefined,
    autoGenerated: undefined as boolean | undefined
  });

  // Load data
  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const [alertsData, summaryData, forecastsData] = await Promise.all([
        EnhancedStockAlertsService.getActiveAlerts({
          severity: filters.severity.length > 0 ? filters.severity : undefined,
          alertType: filters.alertType.length > 0 ? filters.alertType : undefined,
          acknowledged: filters.acknowledged,
          limit: 100
        }),
        EnhancedStockAlertsService.getAlertSummary(),
        EnhancedStockAlertsService.generateStockForecasts(undefined, 30)
      ]);

      setAlerts(alertsData);
      setSummary(summaryData);
      setForecasts(forecastsData.slice(0, 10)); // Top 10 products at risk
    } catch (error) {
      console.error('Error loading alerts data:', error);
    } finally {
      setLoading(false);
    }
  }, [filters]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  // Generate automatic alerts
  const generateAlerts = async () => {
    setLoading(true);
    try {
      const result = await EnhancedStockAlertsService.generateAutomaticAlerts(user?.uid);
      if (result.generated > 0) {
        await loadData();
      }
    } catch (error) {
      console.error('Error generating alerts:', error);
    } finally {
      setLoading(false);
    }
  };

  // Handle alert actions
  const handleAcknowledgeAlert = async (alertId: string) => {
    try {
      await EnhancedStockAlertsService.acknowledgeAlert(alertId, user?.uid);
      await loadData();
    } catch (error) {
      console.error('Error acknowledging alert:', error);
    }
  };

  const handleResolveAlert = async (alertId: string, notes?: string) => {
    try {
      await EnhancedStockAlertsService.resolveAlert(alertId, user?.uid, notes);
      await loadData();
    } catch (error) {
      console.error('Error resolving alert:', error);
    }
  };

  const handleBulkAction = async (action: 'acknowledge' | 'resolve') => {
    if (selectedAlerts.length === 0) return;

    try {
      const updates = action === 'acknowledge' 
        ? { isAcknowledged: true, acknowledgedAt: new Date().toISOString(), acknowledgedBy: user?.uid }
        : { isActive: false, isAcknowledged: true, resolvedAt: new Date().toISOString(), resolvedBy: user?.uid };

      await EnhancedStockAlertsService.bulkUpdateAlerts(selectedAlerts, updates);
      setSelectedAlerts([]);
      await loadData();
    } catch (error) {
      console.error(`Error performing bulk ${action}:`, error);
    }
  };

  const handleSelectAlert = (alertId: string) => {
    setSelectedAlerts(prev => 
      prev.includes(alertId) 
        ? prev.filter(id => id !== alertId)
        : [...prev, alertId]
    );
  };

  const handleSelectAllAlerts = () => {
    if (selectedAlerts.length === alerts.length) {
      setSelectedAlerts([]);
    } else {
      setSelectedAlerts(alerts.map(alert => alert.id!));
    }
  };

  const openActionMenu = (event: React.MouseEvent<HTMLElement>, alert: EnhancedStockAlert) => {
    setActionMenuAnchor(event.currentTarget);
    setActionMenuAlert(alert);
  };

  const closeActionMenu = () => {
    setActionMenuAnchor(null);
    setActionMenuAlert(null);
  };

  const openDetailDialog = (alert: EnhancedStockAlert) => {
    setSelectedAlert(alert);
    setDetailDialogOpen(true);
    closeActionMenu();
  };

  if (loading && !summary) {
    return (
      <Box sx={{ p: 3 }}>
        <LinearProgress />
        <Typography variant="h6" sx={{ mt: 2 }}>Loading stock alerts...</Typography>
      </Box>
    );
  }

  return (
    <Box sx={{ p: 3 }}>
      {/* Header */}
      <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 3 }}>
        <Typography variant="h4" fontWeight="bold">
          Stock Alerts Dashboard
        </Typography>
        <Stack direction="row" spacing={2}>
          <Button
            variant="outlined"
            startIcon={<FilterIcon />}
            onClick={() => setFilterDialogOpen(true)}
          >
            Filters
          </Button>
          <Button
            variant="outlined"
            startIcon={<RefreshIcon />}
            onClick={loadData}
            disabled={loading}
          >
            Refresh
          </Button>
          <Button
            variant="contained"
            startIcon={<NotificationsActiveIcon />}
            onClick={generateAlerts}
            disabled={loading}
          >
            Generate Alerts
          </Button>
        </Stack>
      </Stack>

      {/* Summary Cards */}
      {summary && (
        <Grid container spacing={3} sx={{ mb: 3 }}>
          <Grid item xs={12} sm={6} md={3}>
            <Card>
              <CardContent>
                <Stack direction="row" alignItems="center" spacing={2}>
                  <Badge badgeContent={summary.criticalAlerts} color="error">
                    <ErrorIcon color="error" />
                  </Badge>
                  <Box>
                    <Typography variant="h4" fontWeight="bold">
                      {summary.totalAlerts}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      Total Alerts
                    </Typography>
                  </Box>
                </Stack>
              </CardContent>
            </Card>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <Card>
              <CardContent>
                <Stack direction="row" alignItems="center" spacing={2}>
                  <WarningIcon color="warning" />
                  <Box>
                    <Typography variant="h4" fontWeight="bold">
                      {summary.unacknowledgedAlerts}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      Unacknowledged
                    </Typography>
                  </Box>
                </Stack>
              </CardContent>
            </Card>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <Card>
              <CardContent>
                <Stack direction="row" alignItems="center" spacing={2}>
                  <TrendingDownIcon color="error" />
                  <Box>
                    <Typography variant="h4" fontWeight="bold">
                      {summary.alertsByType.out_of_stock}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      Out of Stock
                    </Typography>
                  </Box>
                </Stack>
              </CardContent>
            </Card>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <Card>
              <CardContent>
                <Stack direction="row" alignItems="center" spacing={2}>
                  <WarningIcon color="warning" />
                  <Box>
                    <Typography variant="h4" fontWeight="bold">
                      {summary.alertsByType.low_stock}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      Low Stock
                    </Typography>
                  </Box>
                </Stack>
              </CardContent>
            </Card>
          </Grid>
        </Grid>
      )}

      {/* Tabs */}
      <Card>
        <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
          <Tabs value={tabValue} onChange={(_, newValue) => setTabValue(newValue)}>
            <Tab label={`Active Alerts (${alerts.length})`} />
            <Tab label={`Stock Forecasts (${forecasts.length})`} />
            <Tab label="Alert Analytics" />
          </Tabs>
        </Box>

        {/* Active Alerts Tab */}
        <TabPanel value={tabValue} index={0}>
          {/* Bulk Actions */}
          {selectedAlerts.length > 0 && (
            <Alert severity="info" sx={{ mb: 2 }}>
              <Stack direction="row" alignItems="center" justifyContent="space-between">
                <Typography>
                  {selectedAlerts.length} alert{selectedAlerts.length > 1 ? 's' : ''} selected
                </Typography>
                <Stack direction="row" spacing={1}>
                  <Button
                    size="small"
                    variant="outlined"
                    onClick={() => handleBulkAction('acknowledge')}
                  >
                    Acknowledge All
                  </Button>
                  <Button
                    size="small"
                    variant="outlined"
                    onClick={() => handleBulkAction('resolve')}
                  >
                    Resolve All
                  </Button>
                </Stack>
              </Stack>
            </Alert>
          )}

          <TableContainer>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell padding="checkbox">
                    <Checkbox
                      checked={alerts.length > 0 && selectedAlerts.length === alerts.length}
                      indeterminate={selectedAlerts.length > 0 && selectedAlerts.length < alerts.length}
                      onChange={handleSelectAllAlerts}
                    />
                  </TableCell>
                  <TableCell>Product</TableCell>
                  <TableCell>Alert Type</TableCell>
                  <TableCell>Severity</TableCell>
                  <TableCell>Current Stock</TableCell>
                  <TableCell>Message</TableCell>
                  <TableCell>Created</TableCell>
                  <TableCell>Status</TableCell>
                  <TableCell>Actions</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {alerts.map((alert) => (
                  <TableRow key={alert.id} hover>
                    <TableCell padding="checkbox">
                      <Checkbox
                        checked={selectedAlerts.includes(alert.id!)}
                        onChange={() => handleSelectAlert(alert.id!)}
                      />
                    </TableCell>
                    <TableCell>
                      <Stack>
                        <Typography variant="body2" fontWeight="medium">
                          {alert.productName}
                        </Typography>
                        {alert.productSku && (
                          <Typography variant="caption" color="text.secondary">
                            SKU: {alert.productSku}
                          </Typography>
                        )}
                      </Stack>
                    </TableCell>
                    <TableCell>
                      <Stack direction="row" alignItems="center" spacing={1}>
                        {getAlertTypeIcon(alert.alertType)}
                        <Typography variant="body2">
                          {alert.alertType.replace('_', ' ').toUpperCase()}
                        </Typography>
                      </Stack>
                    </TableCell>
                    <TableCell>
                      <Chip
                        icon={getSeverityIcon(alert.severity)}
                        label={alert.severity.toUpperCase()}
                        color={getSeverityColor(alert.severity) as any}
                        size="small"
                      />
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2" fontWeight="medium">
                        {alert.currentQuantity}
                      </Typography>
                      {alert.threshold && (
                        <Typography variant="caption" color="text.secondary">
                          Threshold: {alert.threshold}
                        </Typography>
                      )}
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2">
                        {alert.message}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2">
                        {new Date(alert.createdAt).toLocaleDateString()}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Stack spacing={0.5}>
                        {alert.isAcknowledged ? (
                          <Chip label="Acknowledged" color="success" size="small" />
                        ) : (
                          <Chip label="New" color="warning" size="small" />
                        )}
                        {alert.autoGenerated && (
                          <Chip label="Auto" color="info" size="small" />
                        )}
                      </Stack>
                    </TableCell>
                    <TableCell>
                      <IconButton
                        size="small"
                        onClick={(e) => openActionMenu(e, alert)}
                      >
                        <MoreVertIcon />
                      </IconButton>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>

          {alerts.length === 0 && (
            <Box sx={{ textAlign: 'center', py: 4 }}>
              <CheckCircleIcon sx={{ fontSize: 64, color: 'success.main', mb: 2 }} />
              <Typography variant="h6" color="text.secondary">
                No active alerts
              </Typography>
              <Typography variant="body2" color="text.secondary">
                All stock levels are within normal ranges
              </Typography>
            </Box>
          )}
        </TabPanel>

        {/* Stock Forecasts Tab */}
        <TabPanel value={tabValue} index={1}>
          <TableContainer>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell>Product</TableCell>
                  <TableCell>Current Stock</TableCell>
                  <TableCell>Daily Usage</TableCell>
                  <TableCell>Days Until Stockout</TableCell>
                  <TableCell>Reorder Date</TableCell>
                  <TableCell>Suggested Quantity</TableCell>
                  <TableCell>Confidence</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {forecasts.map((forecast) => (
                  <TableRow key={forecast.productId}>
                    <TableCell>
                      <Typography variant="body2" fontWeight="medium">
                        {forecast.productName}
                      </Typography>
                    </TableCell>
                    <TableCell>{forecast.currentStock}</TableCell>
                    <TableCell>{forecast.averageDailyUsage}</TableCell>
                    <TableCell>
                      <Chip
                        label={`${forecast.daysUntilStockout} days`}
                        color={forecast.daysUntilStockout <= 7 ? 'error' : forecast.daysUntilStockout <= 14 ? 'warning' : 'success'}
                        size="small"
                      />
                    </TableCell>
                    <TableCell>
                      {new Date(forecast.recommendedReorderDate).toLocaleDateString()}
                    </TableCell>
                    <TableCell>{forecast.recommendedReorderQuantity}</TableCell>
                    <TableCell>
                      <LinearProgress
                        variant="determinate"
                        value={forecast.confidence * 100}
                        sx={{ width: 60 }}
                      />
                      <Typography variant="caption">
                        {Math.round(forecast.confidence * 100)}%
                      </Typography>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </TabPanel>

        {/* Analytics Tab */}
        <TabPanel value={tabValue} index={2}>
          {summary && (
            <Grid container spacing={3}>
              <Grid item xs={12} md={6}>
                <Card>
                  <CardContent>
                    <Typography variant="h6" gutterBottom>
                      Alerts by Severity
                    </Typography>
                    <Stack spacing={2}>
                      {Object.entries(summary.alertsBySeverity).map(([severity, count]) => (
                        <Stack key={severity} direction="row" justifyContent="space-between" alignItems="center">
                          <Stack direction="row" alignItems="center" spacing={1}>
                            {getSeverityIcon(severity as EnhancedStockAlert['severity'])}
                            <Typography variant="body2">
                              {severity.toUpperCase()}
                            </Typography>
                          </Stack>
                          <Typography variant="h6" fontWeight="bold">
                            {count}
                          </Typography>
                        </Stack>
                      ))}
                    </Stack>
                  </CardContent>
                </Card>
              </Grid>

              <Grid item xs={12} md={6}>
                <Card>
                  <CardContent>
                    <Typography variant="h6" gutterBottom>
                      Top Affected Products
                    </Typography>
                    <Stack spacing={2}>
                      {summary.topAffectedProducts.slice(0, 5).map((product) => (
                        <Stack key={product.productId} direction="row" justifyContent="space-between" alignItems="center">
                          <Box>
                            <Typography variant="body2" fontWeight="medium">
                              {product.productName}
                            </Typography>
                            <Chip
                              label={product.highestSeverity.toUpperCase()}
                              color={getSeverityColor(product.highestSeverity) as any}
                              size="small"
                            />
                          </Box>
                          <Typography variant="h6" fontWeight="bold">
                            {product.alertCount}
                          </Typography>
                        </Stack>
                      ))}
                    </Stack>
                  </CardContent>
                </Card>
              </Grid>
            </Grid>
          )}
        </TabPanel>
      </Card>

      {/* Action Menu */}
      <Menu
        anchorEl={actionMenuAnchor}
        open={Boolean(actionMenuAnchor)}
        onClose={closeActionMenu}
      >
        <MuiMenuItem onClick={() => openDetailDialog(actionMenuAlert!)}>
          <ViewIcon sx={{ mr: 1 }} />
          View Details
        </MuiMenuItem>
        {!actionMenuAlert?.isAcknowledged && (
          <MuiMenuItem onClick={() => {
            handleAcknowledgeAlert(actionMenuAlert!.id!);
            closeActionMenu();
          }}>
            <CheckIcon sx={{ mr: 1 }} />
            Acknowledge
          </MuiMenuItem>
        )}
        <MuiMenuItem onClick={() => {
          handleResolveAlert(actionMenuAlert!.id!);
          closeActionMenu();
        }}>
          <CloseIcon sx={{ mr: 1 }} />
          Resolve
        </MuiMenuItem>
      </Menu>

      {/* Alert Detail Dialog */}
      <Dialog
        open={detailDialogOpen}
        onClose={() => setDetailDialogOpen(false)}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>
          Alert Details
        </DialogTitle>
        <DialogContent>
          {selectedAlert && (
            <Stack spacing={3}>
              <Grid container spacing={2}>
                <Grid item xs={12} sm={6}>
                  <Typography variant="subtitle2" color="text.secondary">
                    Product
                  </Typography>
                  <Typography variant="body1" fontWeight="medium">
                    {selectedAlert.productName}
                  </Typography>
                  {selectedAlert.productSku && (
                    <Typography variant="body2" color="text.secondary">
                      SKU: {selectedAlert.productSku}
                    </Typography>
                  )}
                </Grid>
                <Grid item xs={12} sm={6}>
                  <Typography variant="subtitle2" color="text.secondary">
                    Alert Type
                  </Typography>
                  <Stack direction="row" alignItems="center" spacing={1}>
                    {getAlertTypeIcon(selectedAlert.alertType)}
                    <Typography variant="body1">
                      {selectedAlert.alertType.replace('_', ' ').toUpperCase()}
                    </Typography>
                  </Stack>
                </Grid>
                <Grid item xs={12} sm={6}>
                  <Typography variant="subtitle2" color="text.secondary">
                    Severity
                  </Typography>
                  <Chip
                    icon={getSeverityIcon(selectedAlert.severity)}
                    label={selectedAlert.severity.toUpperCase()}
                    color={getSeverityColor(selectedAlert.severity) as any}
                  />
                </Grid>
                <Grid item xs={12} sm={6}>
                  <Typography variant="subtitle2" color="text.secondary">
                    Current Stock
                  </Typography>
                  <Typography variant="body1" fontWeight="medium">
                    {selectedAlert.currentQuantity}
                  </Typography>
                </Grid>
              </Grid>

              <Divider />

              <Box>
                <Typography variant="subtitle2" color="text.secondary" gutterBottom>
                  Message
                </Typography>
                <Typography variant="body1">
                  {selectedAlert.message}
                </Typography>
              </Box>

              <Box>
                <Typography variant="subtitle2" color="text.secondary" gutterBottom>
                  Recommended Action
                </Typography>
                <Typography variant="body1">
                  {selectedAlert.recommendedAction}
                </Typography>
              </Box>

              {selectedAlert.notes && (
                <Box>
                  <Typography variant="subtitle2" color="text.secondary" gutterBottom>
                    Notes
                  </Typography>
                  <Typography variant="body1">
                    {selectedAlert.notes}
                  </Typography>
                </Box>
              )}

              <Grid container spacing={2}>
                <Grid item xs={12} sm={6}>
                  <Typography variant="subtitle2" color="text.secondary">
                    Created
                  </Typography>
                  <Typography variant="body2">
                    {new Date(selectedAlert.createdAt).toLocaleString()}
                  </Typography>
                </Grid>
                {selectedAlert.acknowledgedAt && (
                  <Grid item xs={12} sm={6}>
                    <Typography variant="subtitle2" color="text.secondary">
                      Acknowledged
                    </Typography>
                    <Typography variant="body2">
                      {new Date(selectedAlert.acknowledgedAt).toLocaleString()}
                    </Typography>
                  </Grid>
                )}
              </Grid>
            </Stack>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDetailDialogOpen(false)}>
            Close
          </Button>
          {selectedAlert && !selectedAlert.isAcknowledged && (
            <Button
              variant="contained"
              onClick={() => {
                handleAcknowledgeAlert(selectedAlert.id!);
                setDetailDialogOpen(false);
              }}
            >
              Acknowledge
            </Button>
          )}
        </DialogActions>
      </Dialog>

      {/* Filter Dialog */}
      <Dialog
        open={filterDialogOpen}
        onClose={() => setFilterDialogOpen(false)}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>Filter Alerts</DialogTitle>
        <DialogContent>
          <Stack spacing={3} sx={{ mt: 1 }}>
            <FormControl fullWidth>
              <InputLabel>Severity</InputLabel>
              <Select
                multiple
                value={filters.severity}
                onChange={(e) => setFilters(prev => ({ ...prev, severity: e.target.value as EnhancedStockAlert['severity'][] }))}
                renderValue={(selected) => (
                  <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                    {selected.map((value) => (
                      <Chip key={value} label={value.toUpperCase()} size="small" />
                    ))}
                  </Box>
                )}
              >
                {['critical', 'high', 'medium', 'low'].map((severity) => (
                  <MenuItem key={severity} value={severity}>
                    {severity.toUpperCase()}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>

            <FormControl fullWidth>
              <InputLabel>Alert Type</InputLabel>
              <Select
                multiple
                value={filters.alertType}
                onChange={(e) => setFilters(prev => ({ ...prev, alertType: e.target.value as EnhancedStockAlert['alertType'][] }))}
                renderValue={(selected) => (
                  <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                    {selected.map((value) => (
                      <Chip key={value} label={value.replace('_', ' ').toUpperCase()} size="small" />
                    ))}
                  </Box>
                )}
              >
                {['out_of_stock', 'low_stock', 'overstock', 'negative_stock', 'reorder_point', 'expiry_warning'].map((type) => (
                  <MenuItem key={type} value={type}>
                    {type.replace('_', ' ').toUpperCase()}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>

            <FormControl fullWidth>
              <InputLabel>Status</InputLabel>
              <Select
                value={filters.acknowledged ?? ''}
                onChange={(e) => setFilters(prev => ({ 
                  ...prev, 
                  acknowledged: e.target.value === '' ? undefined : e.target.value === 'true'
                }))}
              >
                <MenuItem value="">All</MenuItem>
                <MenuItem value="false">Unacknowledged</MenuItem>
                <MenuItem value="true">Acknowledged</MenuItem>
              </Select>
            </FormControl>
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => {
            setFilters({
              severity: [],
              alertType: [],
              acknowledged: undefined,
              autoGenerated: undefined
            });
          }}>
            Clear
          </Button>
          <Button onClick={() => setFilterDialogOpen(false)}>
            Cancel
          </Button>
          <Button variant="contained" onClick={() => {
            setFilterDialogOpen(false);
            loadData();
          }}>
            Apply Filters
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}